/* // This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://libyzgzrdhbmgrsgdkan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYnl6Z3pyZGhibWdyc2dka2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDQ1MzksImV4cCI6MjA2OTEyMDUzOX0.Ytr9g8GpziRxtGt73-BFsXOrJl6gklmkeQjodCguWNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}); */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Correction: utiliser import.meta.env pour Vite
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Vérification en développement
if (import.meta.env.DEV) {
  if (!SUPABASE_URL) console.error("VITE_SUPABASE_URL manquant dans .env.local");
  if (!SUPABASE_PUBLISHABLE_KEY) console.error("VITE_SUPABASE_ANON_KEY manquant dans .env.local");
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
