// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://libyzgzrdhbmgrsgdkan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYnl6Z3pyZGhibWdyc2dka2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDQ1MzksImV4cCI6MjA2OTEyMDUzOX0.Ytr9g8GpziRxtGt73-BFsXOrJl6gklmkeQjodCguWNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});